<?php

namespace Database\Seeders;

use App\Models\CustomerRental;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerRental2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rental = [
             [
                'customer_id' => 22,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => 'N2212031',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 22,
                'CUSTR_NO' => '2',
                'CUSTR_CONTRACT_NO' => 'N2311009',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2023-12-01',
                'CUSTR_END_DATE2' => '2026-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 23,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => 'FPBKK326',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 24,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => 'N2212026',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 25,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => 'N2212030',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 25,
                'CUSTR_NO' => '2',
                'CUSTR_CONTRACT_NO' => 'BKB9309Z',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 26,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => 'VGI.LG.BA.22.083',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 27,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => 'N2212025',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 28,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => 'N2212029',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 29,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => 'N2212028',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2022-12-01',
                'CUSTR_END_DATE2' => '2025-11-30',
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 30,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => '-',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => null,
                'CUSTR_END_DATE2' => null,
                'CUSTR_CONTRACT_YEAR' => '3',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'customer_id' => 31,
                'CUSTR_NO' => '1',
                'CUSTR_CONTRACT_NO' => '-',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '-',
                'CUSTR_FLOOR' => '',
                'CUSTR_ZONE' => '-',
                'CUSTR_SUB_ZONE' => '-',
                'CUSTR_AREA_SQM' => '0',
                 'CUSTR_RENTAL_FEE' => '0',
                'CUSTR_SERVICE_FEE' => '0',
                'CUSTR_EQUIPMENT_FEE' => '0',
                'CUSTR_BEGIN_DATE2' => '2023-12-01',
                'CUSTR_END_DATE2' => '2026-11-30',
                'CUSTR_CONTRACT_YEAR' => '1',
                 'created_by' => 1,
                'updated_by' => 1,
            ],
        ];
        foreach ($rental as $contractData)  {
            
                CustomerRental::create($contractData);
            
        }
    }
}
