<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Customer2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $customers = [
             [
                'CUST_CODE' => 'A2001',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท ทรู อินเทอร์เน็ต คอร์ปอเรชั่น จำกัด',
                'CUST_NAME_EN' => 'TRUE INTERNET CORPORATION CO.,LTD.',
                'CUST_CONTACT' => 'N2212031',
                'CUST_TAXID' => '0105549025026',
                'CUST_ADDRESS_TH1' => '18 อาคารทรูทาวเวอร์ ถนนรัชดาภิเษก แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพมหานคร',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '10310',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
             [
                'CUST_CODE' => 'A2002',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท แฟกซ์ไลท์ จำกัด',
                'CUST_NAME_EN' => 'FAX LITE CO.,LTD.',
                'CUST_CONTACT' => 'FPBKK326',
                'CUST_TAXID' => '0105553003007',
                'CUST_ADDRESS_TH1' => '1291/1 ถนนพหลโยธิน  แขวงพญาไท เขตพญาไท กรุงเทพมหานคร',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '10400',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'CUST_CODE' => 'A2003',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท ซิมโฟนี่ คอมมูนิเคชั่น จำกัด (มหาชน)',
                'CUST_NAME_EN' => 'SYMPHONY COMMUNICATION PUBLIC COMPANY LIMITED',
                'CUST_CONTACT' => 'N2212026',
                'CUST_TAXID' => '0107553000107',
                'CUST_ADDRESS_TH1' => '123 ซันทาวเวอร์ส อาคารบี ชั้น 35-36 ถนนวิภาวดีรังสิต แขวงจอมพล เขตจตุจักร กรุงเทพมหานคร',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '10900',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'CUST_CODE' => 'A2004',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท ทรู มูฟ เอช ยูนิเวอร์แซล คอมมิวนิเคชั่น จำกัด',
                'CUST_NAME_EN' => 'TRUE MOVE H UNIVERSAL COMMUNICATION CO.,LTD.',
                'CUST_CONTACT' => 'N2212030',
                'CUST_TAXID' => '0105553045044',
                'CUST_ADDRESS_TH1' => '18 อาคารทรู ทาวเวอร์ ถนนรัชดาภิเษก แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพมหานคร',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '10310',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
             [
                'CUST_CODE' => 'A2005',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท วีจีไอ จำกัด (มหาชน)',
                'CUST_NAME_EN' => 'VGI PUBLIC COMPANY LIMITED',
                'CUST_CONTACT' => 'VGI.LG.BA.22.083',
                'CUST_TAXID' => '0107555000066',
                'CUST_ADDRESS_TH1' => 'อาคารทีเอสทีทาวเวอร์ชั้นที่9 ถนนวิภาวดีรังสิต แขวงจอมพล เขตจตุจักร กรุงเทพมหานคร',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '10900',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'CUST_CODE' => 'A2006',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท โทรคมนาคมแห่งชาติ จำกัด (มหาชน)',
                'CUST_NAME_EN' => 'NATIONAL TELECOM PUBLIC COMPANY LIMITED',
                'CUST_CONTACT' => 'N2212025',
                'CUST_TAXID' => '0107564000014',
                'CUST_ADDRESS_TH1' => '99 ถนนแจ้งวัฒนะ  แขวงทุ่งสองห้อง เขตหลักสี่ กรุงเทพมหานคร',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '10210',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'CUST_CODE' => 'A2007',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท จัสเทล เน็ทเวิร์ค จำกัด',
                'CUST_NAME_EN' => 'JASTEL NETWORK COMPANY LIMITED',
                'CUST_CONTACT' => 'N2212029',
                'CUST_TAXID' => '0125549007371',
                'CUST_ADDRESS_TH1' => '200 ชั้น 7 ม.4 ถนนแจ้งวัฒนะ ตำบลปากเกร็ด อำเภอปากเกร็ด นนทบุรี',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '11120',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'CUST_CODE' => 'A2008',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท ยูไนเต็ด อินฟอร์เมชั่น ไฮเวย์ จำกัด',
                'CUST_NAME_EN' => 'UNITED INFORMATION HIGHWAY CO., LTD.',
                'CUST_CONTACT' => 'N2212028',
                'CUST_TAXID' => '0105539053094',
                'CUST_ADDRESS_TH1' => '499 ถนนกำแพงเพชร 6  แขวงลาดยาว   เขตจตุจักร  กรุงเทพมหานคร',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '10900',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'CUST_CODE' => 'A2009',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท ยูนิ. ชาร์ม (ประเทศไทย) จำกัด',
                'CUST_NAME_EN' => 'UNI.CHARM (THAILAND) CO., LTD.',
                'CUST_CONTACT' => '-',
                'CUST_TAXID' => '0105530035751',
                'CUST_ADDRESS_TH1' => '105 หมู่ 9 ตำบลบางวัว อำเภอบางปะกง จังหวัดฉะเชิงเทรา',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '24130',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'CUST_CODE' => 'A2010',
                'CUST_ABB' => '',
                'CUST_NAME_TH' => 'บริษัท นิปปอน พาร์คกิ้ง ดีเวลลอปเมนท์ (ประเทศไทย) จำกัด',
                'CUST_NAME_EN' => 'NIPPON PARKING DEVELOPMENT (THAILAND) COMPANY LIMITED',
                'CUST_CONTACT' => '-',
                'CUST_TAXID' => '0105553122294',
                'CUST_ADDRESS_TH1' => '952 อาคารรามาแลนด์ ชั้น 17 ถนนพระราม 4 แขวงสุริยวงศ์ เขตบางรัก กรุงเทพมหานคร',
                'CUST_ADDRESS_TH2' => '',
                'CUST_ADDRESS_EN1' => '',
                'CUST_ADDRESS_EN2' => '',
                'CUST_ZIPCODE' => '10500',
                'CUST_FLOOR' => '',
                'CUST_CALVAT' => 'Y',
                'CUST_CALWHTAX' => 'Y',
                'CUST_INVAUTO' => 'Y',
                'CUST_BRANCH' => 'Head Office',
                  'created_by' => 1,
                'updated_by' => 1,
            ],
        ];
           foreach ($customers as $contractData)  {
            // Check if a customer with the same cust_code exists
              $existingCustomer = Customer::where('cust_code', $contractData['CUST_CODE'])->first();
            // If the customer doesn't exist, create a new one
            if (is_null($existingCustomer)) {
                Customer::create($contractData);
            }
        }
    }
}
