<?php

namespace Database\Seeders;

use App\Models\CustomerRental;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerRentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      
        $contracts = [
            [
                'customer_id' => 1,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2307007',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => 'G03',
                'CUSTR_AREA_SQM' => 71,
                'CUSTR_RENTAL_FEE' => 320,
                'CUSTR_SERVICE_FEE' => 480,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/10/2023')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/09/2026')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 2,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212002',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1101',
                'CUSTR_AREA_SQM' => 135,
                'CUSTR_RENTAL_FEE' => 256,
                'CUSTR_SERVICE_FEE' => 384,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 3,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212003',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1104',
                'CUSTR_AREA_SQM' => 99,
                'CUSTR_RENTAL_FEE' => 150,
                'CUSTR_SERVICE_FEE' => 200,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 4,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212004',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1106,1107',
                'CUSTR_AREA_SQM' => 238,
                'CUSTR_RENTAL_FEE' => 150,
                'CUSTR_SERVICE_FEE' => 200,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 5,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N-2404001',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1105',
                'CUSTR_AREA_SQM' => 70,
                'CUSTR_RENTAL_FEE' => 200,
                'CUSTR_SERVICE_FEE' => 300,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/05/2024')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 1.7,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 6,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212007',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1207',
                'CUSTR_AREA_SQM' => 135,
                'CUSTR_RENTAL_FEE' => 150,
                'CUSTR_SERVICE_FEE' => 200,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 7,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212008',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1211',
                'CUSTR_AREA_SQM' => 66,
                'CUSTR_RENTAL_FEE' => 150,
                'CUSTR_SERVICE_FEE' => 200,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 8,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212009',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1212',
                'CUSTR_AREA_SQM' => 103,
                'CUSTR_RENTAL_FEE' => 150,
                'CUSTR_SERVICE_FEE' => 200,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 9,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212010',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1402,1403',
                'CUSTR_AREA_SQM' => 178,
                'CUSTR_RENTAL_FEE' => 174,
                'CUSTR_SERVICE_FEE' => 232,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
             [
                'customer_id' => 10,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212011',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1404',
                'CUSTR_AREA_SQM' => 99,
                'CUSTR_RENTAL_FEE' => 272,
                'CUSTR_SERVICE_FEE' => 408,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 11,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2308008-1',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1411',
                'CUSTR_AREA_SQM' => 66,
                'CUSTR_RENTAL_FEE' => 220,
                'CUSTR_SERVICE_FEE' => 330,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/09/2023')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '31/07/2024')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 0.11,
                'created_by' => 1,
                'updated_by' => 1
            ],
             [
                'customer_id' => 11,
                'CUSTR_NO' => 2,
                'CUSTR_CONTRACT_NO' => 'N2308008-2',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1411',
                'CUSTR_AREA_SQM' => 66,
                'CUSTR_RENTAL_FEE' => 256,
                'CUSTR_SERVICE_FEE' => 384,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/08/2024')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 1.4,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 12,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212013',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1501,1502',
                'CUSTR_AREA_SQM' => 227,
                'CUSTR_RENTAL_FEE' => 256,
                'CUSTR_SERVICE_FEE' => 384,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 13,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212014',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1508',
                'CUSTR_AREA_SQM' => 167,
                'CUSTR_RENTAL_FEE' => 272,
                'CUSTR_SERVICE_FEE' => 408,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 14,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212015',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1509,1510',
                'CUSTR_AREA_SQM' => 238,
                'CUSTR_RENTAL_FEE' => 260,
                'CUSTR_SERVICE_FEE' => 390,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 15,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212017',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1514,1515',
                'CUSTR_AREA_SQM' => 286,
                'CUSTR_RENTAL_FEE' => 260,
                'CUSTR_SERVICE_FEE' => 390,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
             [
                'customer_id' => 16,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212018-1',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1601,1602',
                'CUSTR_AREA_SQM' => 436,
                'CUSTR_RENTAL_FEE' => 220,
                'CUSTR_SERVICE_FEE' => 330,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2023')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 1,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 16,
                'CUSTR_NO' => 2,
                'CUSTR_CONTRACT_NO' => 'N2212018-2',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1601,1602',
                'CUSTR_AREA_SQM' => 436,
                'CUSTR_RENTAL_FEE' => 240,
                'CUSTR_SERVICE_FEE' => 360,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2023')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2024')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 1,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 17,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212020',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1805',
                'CUSTR_AREA_SQM' => 298,
                'CUSTR_RENTAL_FEE' => 252,
                'CUSTR_SERVICE_FEE' => 378,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 18,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N-2404002-1',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => 'G01',
                'CUSTR_AREA_SQM' => 408,
                'CUSTR_RENTAL_FEE' => 380,
                'CUSTR_SERVICE_FEE' => 570,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => Carbon::createFromFormat('d/m/Y', '01/06/2024')->format('Y-m-d'),
                'CUSTR_END_DATE2' => Carbon::createFromFormat('d/m/Y', '30/11/2024')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 0.6,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 18,
                'CUSTR_NO' => 2,
                'CUSTR_CONTRACT_NO' => 'N-2404002-2',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1701,1702',
                'CUSTR_AREA_SQM' => 436,
                'CUSTR_RENTAL_FEE' => 244,
                'CUSTR_SERVICE_FEE' => 366,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '1/6/2024')->format('Y-m-d'),
                'CUSTR_END_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '30/11/2024')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 0.6,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 18,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2302004-1',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => 'M01',
                'CUSTR_AREA_SQM' => 398,
                'CUSTR_RENTAL_FEE' => 300,
                'CUSTR_SERVICE_FEE' => 450,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '1/03/2023')->format('Y-m-d'),
                'CUSTR_END_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 1.9,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 18,
                'CUSTR_NO' => 2,
                'CUSTR_CONTRACT_NO' => 'N2302004-2',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1102-3,1114-15,1801-4,1806-8,2001-8,2101-8,2202',
                'CUSTR_AREA_SQM' => 5676,
                'CUSTR_RENTAL_FEE' => 258,
                'CUSTR_SERVICE_FEE' => 387,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '1/03/2023')->format('Y-m-d'),
                'CUSTR_END_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 1.9,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 19,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212012',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1408',
                'CUSTR_AREA_SQM' => 167,
                'CUSTR_RENTAL_FEE' => 228,
                'CUSTR_SERVICE_FEE' => 342,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '1/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 19,
                'CUSTR_NO' => 2,
                'CUSTR_CONTRACT_NO' => 'N2304005',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1406,1407',
                'CUSTR_AREA_SQM' => 238,
                'CUSTR_RENTAL_FEE' => 228,
                'CUSTR_SERVICE_FEE' => 342,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '1/6/2023')->format('Y-m-d'),
                'CUSTR_END_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 2.6,
                'created_by' => 1,
                'updated_by' => 1
            ],
            [
                'customer_id' => 20,
                'CUSTR_NO' => 1,
                'CUSTR_CONTRACT_NO' => 'N2212019',
                'CUSTR_TOWER' => 'A',
                'CUSTR_UNIT' => '1605,1606',
                'CUSTR_AREA_SQM' => 456,
                'CUSTR_RENTAL_FEE' => 228,
                'CUSTR_SERVICE_FEE' => 342,
                'CUSTR_EQUIPMENT_FEE' => 0,
                'CUSTR_BEGIN_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '1/12/2022')->format('Y-m-d'),
                'CUSTR_END_DATE2' => \Carbon\Carbon::createFromFormat('d/m/Y', '30/11/2025')->format('Y-m-d'),
                'CUSTR_CONTRACT_YEAR' => 3,
                'created_by' => 1,
                'updated_by' => 1
            ]
        ];

        // Insert data using Eloquent
       
        foreach ($contracts as $contractData)  {
            // Check if a customer with the same cust_code exists
            $existingCustomer = CustomerRental::where('CUSTR_CONTRACT_NO', $contractData['CUSTR_CONTRACT_NO'])->first();
            
            // If the customer doesn't exist, create a new one
            if (is_null($existingCustomer)) {
                CustomerRental::create($contractData);
            }
        }
    }

}
